version: '2'
services:
  db:
    image: kiasaki/alpine-postgres
    volumes:
      - ./pgdata:/pgdata
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ruby_fullstack_development
      POSTGRES_USER: postgres
      PGDATA: /pgdata
  redis:
    image: redis
  web:
    image: braidn/ruby-full-stack:2.3.1
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    tty: true
    stdin_open: true
    links:
      - db
      - redis
    volumes:
      - .:/src/repo
      - ./keys:/root/.ssh/
    volumes_from:
      - bundle_cache
      - npm_cache
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      REDIS_URL: redis://redis:6379
  cable:
    links:
      - redis
    image: braidn/ruby-full-stack:2.3.1
    command: bundle exec puma --pidfile ./tmp/pids/cable.pid -p 28080 cable/config.ru
    ports:
      - '28080:28080'
    volumes_from:
      - bundle_cache
    volumes:
      - .:/src/repo
    env_file:
      - .env
  npm_cache:
    image: busybox
    volumes:
      - /src/repo/node_modules
  bundle_cache:
    image: busybox
    volumes:
      - /src/repo/.bundle
