# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b677bb54b02ab01aa51e3ce76d0a054290331cfc46158a53c109f0e01221be5ee42afd837191d759e659c03dd9433209e1e1426a11645e33afca14674944534

test:
  secret_key_base: aa77bfe52cd7bd2fba678b9655a03948707f8bd220a4782ac903df2371048ba1e7a8cadee11c2851191954d4ce5af198793fc7ad9e68cdff576b38c07c081cd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
